name : Create Figma Tokens PR

# match the branch you put in your Figma Tokens Sync in the next step
on:
	push:
		branches:
			- figma-tokens

jobs:
	pull-request:
		runs-on: ubuntu-lates
		steps:
		-uses: action/checkout@v2

		-name: Create Pull Request
		uses : repo-sync/pull-request@v2
		with:
			destination_branch: "main" #match with default branch
			pr_title: "Figma Tokens Update"
			pr_body: "✨ Figma Tokens were updated in Figma This PR was created to update the code"
			github_token: ${{ secrets.GH_PAT }}